test-python3:
    image: python:3
    script:
        - python setup.py test

test-python2:
    image: python:2
    before_script:
        - pip install mock
    script:
        - python setup.py test
